language: node_js
node_js: 14
branches:
  only: main
cache:
  npm: false
  directories:
    - '.yarn/cache'
deploy:
  keep-history: true
  local-dir: build
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
  github-token:
    secure:
  on:
    branch: main
install:
  - yarn
script:
  - yarn build
